added a step to find a record in an array
apptreesoftware/step_library pull request #12
Opened 2019-07-18 17:38 UTC by alexisandreason

2019-07-22 21:03 UTC, matthewtsmith requested changes

2019-07-22 21:03 UTC, matthewtsmith commented on common_pkg/main.go
> +	step.Register(FindInArray{})
This should be removed

2019-07-22 22:30 UTC, alexisandreason commented on common_pkg/main.go
> +	step.Register(FindInArray{})
updated

2019-08-06 22:01 UTC, matthewtsmith approved these changes

2019-08-06 22:04 UTC, merged